export const REGISTER = "REGISTER"
export const SIGNIN = "SIGNIN"
export const GETALLMATCHES = "GETALL"
export const USERNAMECLICKED = "USERNAMECLICKED"
export const GETMESSAGES = "GETMESSAGES"


export const FETCH_REGISTER = "FETCH_REGISTER"
export const FETCH_REGISTER_SUCCESS = "FETCH_REGISTER_SUCCESS"
export const FETCH_REGISTER_FAILURE = "FETCH_REGISTER_FAILURE"