export const REGISTER = "REGISTER"
export const SIGNIN = "SIGNIN"
export const GETALL = "GETALL"


export const FETCH_REGISTER = "FETCH_REGISTER"
export const FETCH_REGISTER_SUCCESS = "FETCH_REGISTER_SUCCESS"
export const FETCH_REGISTER_FAILURE = "FETCH_REGISTER_FAILURE"